-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : dim. 02 oct. 2022 à 16:36
-- Version du serveur : 5.7.33
-- Version de PHP : 8.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `anime-list`
--

-- --------------------------------------------------------

--
-- Structure de la table `animes`
--

CREATE TABLE `animes` (
  `id` int(11) NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `type` varchar(8) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `year` int(4) NOT NULL,
  `synopsis` longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `studio` varchar(100) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `episodes` int(11) NOT NULL,
  `cover` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Déchargement des données de la table `animes`
--

INSERT INTO `animes` (`id`, `title`, `type`, `year`, `synopsis`, `studio`, `episodes`, `cover`, `created_at`) VALUES
(1, 'Cowboy Bebop', 'TV', 1998, 'Enter a world in the distant future, where Bounty Hunters roam the solar system. Spike and Jet, bounty hunting partners, set out on journeys in an ever struggling effort to win bounty rewards to survive.\r\n\r\nWhile traveling, they meet up with other very interesting people. Could Faye, the beautiful and ridiculously poor gambler, Edward, the computer genius, and Ein, the engineered dog be a good addition to the group?', 'Sunrise', 26, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1-CXtrrkMpJ8Zq.png', '2022-09-17 09:38:04'),
(2, 'Shingeki no Kyojin\r\n', 'TV', 2013, 'Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans.\r\n\r\nFlash forward to the present and the city has not seen a titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.\r\n\r\n(Source: MangaHelpers)', 'Wit Studio\r\n', 25, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-C6FPmWm59CyP.jpg', '2022-09-17 09:38:04'),
(3, 'Shingeki no Kyojin 2', 'TV', 2017, 'Eren Jaeger swore to wipe out every last Titan, but in a battle for his life he wound up becoming the thing he hates most. With his new powers, he fights for humanity', 'Wit Studiox', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20958-HuFJyr54Mmir.jpg', '2022-09-17 09:38:04'),
(4, 'Shingeki no Kyojin 3\r\n', 'TV', 2018, 'Eren and his companions in the 104th are assigned to the newly-formed Levi Squad, whose assignment is to keep Eren and Historia safe given Eren\'s newly-discovered power and Historia\'s knowledge and pedigree. Levi and Erwin have good reason to be concerned, because the priest of the Church that Hanji had hidden away was found tortured to death, making it clear that the Military Police are involved with the cover-up. Things get more harrowing when the MPs make a move on Erwin and the Levi Squad narrowly avoids capture. Eren is also having problems with his Titan transformation, and a deadly killer has been hired to secure Eren and Historia, one Levi knows all too well from his youth.\r\n\r\n(Source: Anime News Network)', 'Wit Studio', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx99147-5RXELRvwjFl6.jpg', '2022-09-17 09:38:04'),
(5, 'Kimetsu no Yaiba', 'TV', 2019, 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.\r\n\r\n(Source: Crunchyroll)', 'Ufotable', 26, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-PEn1CTc93blC.jpg', '2022-09-17 09:38:04'),
(6, 'Azumanga Daiou THE ANIMATION', 'TV', 2002, 'Ten year old child prodigy, Chiyo Mihama, is finding it tough fitting in at high school with the girls five years her elder: Osaka (dimwitted with a weird take on the world), Tomo (a powder keg that goes off at a moment’s notice), Kagura (the competitive athlete of the bunch), Yomi (the hothead), and Sakaki (timid and obsessed with a love of animals that isn’t reciprocated). Together with their teacher, they navigate the rough waters and fun times of high school.\r\n\r\n(Source: Sentai Filmworks)', 'J.C. Staff', 26, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx66-1LTNhVTnttZv.png', '2022-10-02 12:51:03'),
(7, 'Ginga Tetsudou 999', 'TV', 1978, 'In a distant future, Tetsuro is a human boy who wants his body replaced with a robotic one. This is possible, but to do so he has to reach the Immortal Planet onboard the space train Galaxy Express 999. Maetel, a beautiful and mysterious blonde woman dressed in Russian style, joins him in the long journey through space. Every episode sees our heroes arriving in a new planet\'s space train station.\r\n\r\n(Source: Anime News Network)', 'Toei Animation', 113, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1491-XfYiHNYKDR2P.jpg', '2022-09-17 09:38:04'),
(8, 'Uchuu Kaizoku Captain Harlock', 'TV', 1978, 'The year is 2977. Mankind has become complacent and stagnant. All work is done by machines, while humans spend all their time on entertainment. But when a mysterious invader from the stars catches Earth unawares, only the legendary space pirate Captain Harlock and the crew of the Arcadia have the will to stand against them.\r\n\r\n(Source: Anime News Network)', 'Toei Animation', 42, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1000-dxR1NyPZXVbm.png', '2022-09-17 09:38:04'),
(9, 'Naruto', 'TV', 2002, 'Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi\'s rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto.  Shunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way.  (Source: MAL Rewrite)', 'Studio Pierrot', 220, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-YJvLbgJQPCoI.jpg', '2022-09-24 12:35:29'),
(10, 'NARUTO: Shippuuden', 'TV', 2007, 'Naruto: Shippuuden is the continuation of the original animated TV series Naruto. The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as he has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.  (Source: Anime News Network)', 'Studio Pierrot', 500, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-Az5gbEdWeotG.png', '2022-09-24 12:41:58'),
(11, 'Urusei Yatsura', 'TV', 1981, 'Urusei Yatsura concerns the tempestuous relationship between two focal characters: Ataru Moroboshi who is possibly the most unfaithful, unlucky and lecherous idiot to have ever been born, and there\'s Lum, a tigerskin-bikini clad alien package of sex appeal, jealousy and electricity who\'s fallen for him. The series chronicles the misadventures of these two stubborn teenagers along with a veritable entourage of weird characters. Among these characters is the richest boy on the planet, a superhuman schoolgirl, a fire-breathing baby, a powerful priestess/school nurse, a cute and psychotic alien vixen with a split personality, a gender-bending martial artist, an alien biker chick, an ice queen of Neptune, a deranged monk, a giant ghost cat and hundreds of other lunatic personalities; aliens, humans and inhumans alike interract in endless hysteria in a town named Tomobiki.', 'Studio Pierrot', 195, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx1293-T6Ev080pKoum.jpg', '2022-09-17 09:38:04'),
(12, 'Cardcaptor Sakura', 'TV', 1998, 'One day, Kinomoto Sakura, a 4th grader stumbles upon the mysterious book of Clow. Upon opening it and reading the name of The Windy aloud, Sakura scatters the cards to the winds. Sakura is elected and appointed by Keroberos, Guardian of the Cards to capture the remaining cards. With her friend Tomoyo and rival Syaoran, Sakura begins an adventure that will forever change her.', 'MADHOUSE', 70, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx232-ZqAR0y2xkowj.png', '2022-09-17 09:38:04'),
(13, 'Turn A Gundam', 'TV', 1999, 'This story is set thousands of years in the future. The people of Earth have forgotten the space wars of the past, reverting back to a pre-industrial existence. But the lunar settlers known as the Moonrace, who have retained their high technology, now plan to seize their mother planet for themselves. As the war of the worlds begins, a young Moonrace citizen named Loran Cehack, pilot of the legendary Turn A Gundam, struggles to bridge the gap between humanity\'s long-separated branches.\r\n\r\n(Source: GundamOfficial)', 'Sunrise', 50, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx95-5okHk1B0VKro.jpg', '2022-09-17 09:38:04'),
(14, 'Akage no Anne', 'TV', 1979, 'Anne is an orphan full of imagination. When she arrives at her new home she learns that sometimes you have to be a sensible person too; at the same time her unique character changes, or at least attracts, the people around her. The story covers Anne\'s growth from about eleven to seventeen years old as she makes friends, goes to school and studies. At a difficult point in her life, Anne will have to make a hard choice and perhaps find a new dream.', 'Nippon Animation', 50, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx283-SfZh7XERqZjy.png', '2022-09-17 09:38:04'),
(15, 'Lycoris Recoil', 'TV', 2002, '“LycoReco” is a café with a traditional Japanese twist located in downtown Tokyo. But the delicious coffee and sugary sweets are not the only orders this café takes! From delivering packages short distances, to pick-ups and drop-offs on the lonely streets at night, to zombies and giant monster extermination…?! Whatever your problem, we\'re here to help! We will solve any kind of \"trouble\" you may have!  Waiting for you are the ever-smiling poster-girl and the cool, serious newcomer. A petite girl who never wants to work and a young woman approaching thirty who wants to get married. And the manager is a nice guy who’s obsessed with Japan!  Whatever your order is, leave it all up to us?  (Source: Official Site)', 'A-1 Pictures', 13, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143270-iZOJX2DMUFMC.jpg', '2022-09-26 14:59:15'),
(16, 'Princess Tutu', 'TV', 2002, 'In a fairy tale come to life, the clumsy, sweet, and gentle Ahiru (Japanese for \'duck\') seems like an unlikely protagonist. In reality, Ahiru is just as magical as the talking cats and crocodiles that inhabit her town - for Ahiru really is a duck! Transformed by the mysterious Drosselmeyer into a human girl, Ahiru soon learns the reason for her existence. Using her magical egg-shaped pendant, Ahiru can transform into Princess Tutu - a beautiful and talented ballet dancer whose dances relieve people of the turmoil in their hearts. With her newfound ability, Ahiru accepts the challenge of collecting the lost shards of her prince\'s heart, for long ago he had shattered it in order to seal an evil raven away for all eternity.\r\n\r\nPrincess Tutu is a tale of heroes and their struggle against fate. Their beliefs, their feelings, and ultimately their actions will determine whether this fairy tale can reach its \"happily ever after.\"', 'Hal Film Maker', 26, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx721-yuQXUgrLoQ96.jpg', '2022-09-30 09:16:14'),
(17, 'Cardfight!! Vanguard: will+Dress', 'TV', 2022, 'The third season of Cardfight!! Vanguard: overDress.\r\n\r\nTeen runaway, Yu-yu, whose empathy is matched only by his inability to say no to others, meets Megumi Okura. Megumi invites him to a mysterious destination, Dreamland Wonder Hill amusement park. There, he discovers intensely competitive groups like Team Blackout gather to play an exhilarating and alluring game called Vanguard. Yu-yu is drawn into this world of high stakes competition where he must balance new friendships against his drive for victory.\r\n\r\n(Source: Sentai Filmworks)', 'Kinema Citrus,		Studio JEMI, GIFTanimation', 13, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx139212-2dds9fnqW3WD.jpg', '2022-10-02 12:43:28'),
(18, 'DEATH NOTE', 'TV', 2006, 'Light Yagami is a genius high school student who is about to learn about life through a book of death. When a bored shinigami, a God of Death, named Ryuk drops a black notepad called a Death Note, Light receives power over life and death with the stroke of a pen. Determined to use this dark gift for the best, Light sets out to rid the world of evil… namely, the people he believes to be evil. Should anyone hold such power?The consequences of Light’s actions will set the world ablaze.(Source: Viz Media)', 'MADHOUSE', 37, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1535-lawCwhzhi96X.jpg', '2022-09-30 09:42:00'),
(19, 'Akatsuki no Yona', 'TV', 2014, 'Since Yona is the only princess of a grand kingdom, she has been raised with great care by her doting father and protected by her childhood friend/guard Hak and others. However, her fate changes on her 16th birthday, when her beloved cousin Soo-won murders her father to claim the throne. She flees the castle to Hak\'s hometown and begins her new life.\r\n\r\n(Source: Anime News Network)', 'Studio Pierrot', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20770-brCDvhTXlums.png', '2022-10-01 19:47:17'),
(20, 'SPY×FAMILY Part 2', 'TV', 2022, 'The second half of SPYxFAMILY.', 'Wit Studio, CloverWorks', 13, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx142838-ECZSqfknAqAT.jpg', '2022-10-01 20:02:40'),
(21, 'SPY×FAMILY', 'TV', 2022, 'Everyone has a part of themselves they cannot show to anyone else.\r\n\r\nAt a time when all nations of the world were involved in a fierce war of information happening behind closed doors, Ostania and Westalis had been in a state of cold war against one another for decades. The Westalis Intelligence Services\' Eastern-Focused Division (WISE) sends their most talented spy, \"Twilight,\" on a top-secret mission to investigate the movements of Donovan Desmond, the chairman of Ostania\'s National Unity Party, who is threatening peace efforts between the two nations.\r\n\r\nThis mission is known as \"Operation Strix.\" It consists of \"putting together a family in one week in order to infiltrate social gatherings organized by the elite school that Desmond\'s son attends.\"\r\n\r\n\"Twilight\" takes on the identity of psychiatrist Loid Forger and starts looking for family members. But Anya, the daughter he adopts, turns out to have the ability to read people\'s minds, while his wife, Yor, is an assassin! With it being in each of their own interests to keep these facts hidden, they start living together while concealing their true identities from one another.\r\nWorld peace is now in the hands of this brand-new family as they embark on an adventure full of surprises.\r\n\r\n(Source: Crunchyroll)', 'Wit Studio, CloverWorks', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx140960-vN39AmOWrVB5.jpg', '2022-10-01 20:03:09'),
(22, 'Cyberpunk: Edgerunners', 'TV', 2022, 'An original anime series set in in the universe of Cyberpunk 2077.\r\n\r\nCYBERPUNK: EDGERUNNERS tells a standalone, 10-episode story about a street kid trying to survive in a technology and body modification-obsessed city of the future. Having everything to lose, he chooses to stay alive by becoming an edgerunner—a mercenary outlaw also known as a cyberpunk.\r\n\r\n(Source: CD PROJEKT RED)', 'Trigger', 10, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx120377-p2PmPHb6Zwk0.jpg', '2022-10-02 08:53:43'),
(23, 'ONE PIECE', 'TV', 1999, 'Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King.\r\n\r\nEnter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece.', 'Toei Animation', 1036, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx21-tXMN3Y20PIL9.jpg', '2022-10-02 08:56:48'),
(24, 'Chainsaw Man', 'TV', 2022, 'Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by harvesting devil corpses with Pochita.\r\n\r\nOne day, Denji is betrayed and killed. As his consciousness fades, he makes a contract with Pochita and gets revived as \"Chainsaw Man\" — a man with a devil\'s heart.\r\n\r\n(Source: Crunchyroll)', 'MAPPA', 12, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx127230-FlochcFsyoF4.png', '2022-10-02 10:26:20'),
(25, 'Yuusha-Ou GaoGaiGar', 'TV', 1997, 'In the year 2005, a race of alien monsters called Zonders emerge from underground and launch a series of attacks on the city of Tokyo. The only defense against these creatures is the secret agency known as the Gutsy Geoid Guard (or 3G) and their ultimate weapon, the awesome giant robot GaoGaiGar. GaoGaiGar\'s pilot, Guy Shishio, is a former astronaut who was nearly killed two years before when the Zonders first crashed to earth. Guy\'s life was spared when a mysterious robot lion called Galeon pulled him from the burning shuttle and brought him to Earth. Guy\'s father, Leo, then used Galeon\'s technology to rebuild his shattered son as a cyborg, in the hopes that he could stop the aliens when they appear. Now, with Galeon as its core, GaoGaiGar fights to protect Earth. He is aided by a team of transforming robots and by a young boy named Mamoru, who has the power to purify the Zonders\' cores, and seems to be connected to the mysterious Galeon.\r\n\r\n(Source: Anime News Network)', 'Sunrise', 49, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx890-opmekyhFfZO9.jpg', '2022-10-02 10:26:50'),
(26, 'Ojamajo Doremi', 'TV', 1999, 'Doremi Harukaze, 3rd grade student at Misora Elementary School, claims to be the world\'s unluckiest pretty girl. Fascinated by witchcraft, she is drawn into a mysterious shop where she meets Majo Rika and is able to deduce that this lady is in fact a real witch. Being exposed by a human triggers a curse that transforms witches into magical frogs. To regain her original body, Rika must turn Doremi into a witch by teaching her how to use magic. Thrilled by this odd development, Harukaze becomes a witch apprentice. Unfortunately, her two best friends, Hazuki Fujiwara and Aiko Senoo, discover that Doremi has become a magic user. Afraid that Harukaze might become a magical frog too, Majo Rika recruits both Hazuki and Aiko and makes them witch apprentices too. The trio has lots of adventures as they try to triumph the necessary trials to become real witches.\r\n\r\n(Source: Anime News Network)', 'Toei Animation', 51, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx350-qhqB286Za32Y.jpg', '2022-10-02 10:27:17'),
(27, 'Maison Ikkoku', 'TV', 1986, 'Maison Ikkoku is a romantic comedy series created by Rumiko Takahashi. The story centers around the development of the relationship between Kyoko Otonashi and Yusaku Godai. Kyoko is a recent widow who moves into the apartment house Ikkoku-kan where she becomes the manager. Godai is a wanna-be student (\"ronin\") struggling with college entrance exams.\r\n\r\nWhen they meet, it\'s love at first sight—for Godai anyway. Along the way, the other tentants, the mysterious Yotsuya, the seemingly alcoholic Ichinose, and the brash Akemi, watch and occasionally take part to make their lives more interesting. To complicate matters further, the wealthy tennis coach Shun Mitaka has his eye on Kyoko, while Godai is pursued by both Nanao Kozue and Ibuki Yagami. Covering a wide range of emotions from hysterically funny to painfully sad, Maison Ikkoku—all 96 episodes—is well worth seeing.', 'Studio DEEN', 96, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx1453-mghhMKzxEVcQ.jpg', '2022-10-02 10:27:51'),
(28, 'Mawaru Penguindrum', 'TV', 2011, 'Once you make a decision, does the universe conspire to make it happen? Is destiny a matter of chance, a matter of choice or the complex outcome of thousands of warring strands of fate? All twins Kanba and Shoma know is that when their terminally ill sister Himari collapses at the aquarium, her death is somehow temporarily reversed by the penguin hat that she had asked for. It\'s a provisional resurrection, however, and it comes at a price: to keep Himari alive they need to find the mysterious Penguin Drum. In order to do that, they must first find the links to a complex interlocking chain of riddles that has wrapped around their entire existence, and unravel the knots that tie them to mystifying diary and a baffling string of strangers and semi-acquaintances who all have their own secrets, agendas and \"survival strategies.\" And in order for Himari to live, someone else\'s chosen destiny will have to change. It\'s a story of love, fate, life, death... and Penguins!\r\n\r\n(Source: Sentai Filmworks', 'Brain\'s Base', 24, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx10721-2QWmrqbmyYil.jpg', '2022-10-02 10:28:18'),
(29, 'Shoujo Kakumei Utena', 'TV', 1997, 'Just after Utena\'s parents died she was consoled by a prince who gave her a ring with a rose crest on it. Utena was so impressed by the Prince that she vowed to become one herself one day. A few years later Utena is attending Ohtori Academy where she gives all the teachers headaches because she dresses in a boys uniform so she can be like the prince she met long ago.\r\n\r\nAfter Utena\'s friend is insulted by a member of the Student Council, Utena fights in a duel for her friends honor. Utena\'s rose crest allows her to enter the dueling arena where Utena wins the duel and becomes engaged to the Rose Bride. Unknowingly, Utena is pulled into a series of duels with other members of the Student Council for the possession of the Rose Bride. As she becomes fond of Anthy, the Rose Bride, she must fight to keep her friend safe and to discover the horrifying secret behind Ohtori Academy.\r\n\r\n(Source: Anime News Network)', 'J.C. Staff', 39, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx440-7muMZaQ7r84M.jpg', '2022-10-02 10:28:49'),
(30, 'Uchuu Senkan Yamato', 'TV', 1974, 'In the distant future, the war between the human race and the Gamilon has taken its toll on the planet Earth. Constant bombardment of radioactive asteroids has rendered the planet\'s atmosphere uninhabitable. As a means of relief aid, Queen Starsha of the planet Iscandar offers the Earth Forces a device that can completely neutalize the radiation off the planet. For this task, the space battleship Yamato is launched from the remains of its World War II ancestor on a 148,000 light-year journey. However, the crew of the Yamato has only one Earth year to travel to Iscandar and back, or the human race will come to an end.\r\n\r\n(Source: Anime News Network)', 'Group TAC', 26, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx1650-v2eMjvOfnLCc.jpg', '2022-10-02 10:29:30'),
(31, 'Saraba Uchuu Senkan Yamato: Ai no Senshitachi', 'Movie', 1978, 'In the year 2201, one year after the Yamato saved Earth from radioactive contamination, a new threat emerges. The Yamato makes its final journey to save the Earth from this new threat.\r\n\r\nEarth has almost recovered from the battle against Gamilus, and reconstruction has expanded to the other planets. When former Yamato crew-mates discover a strange, garbled message that seems to be coming from a white comet headed towards Earth, they hijack their old space fortress and begin a new battle.\r\n\r\n(Source: AnimeNfo)', 'Group TAC', 1, 'https://cdn.myanimelist.net/images/anime/7/83047.jpg', '2022-10-02 10:30:30'),
(32, 'Uchuu Senkan Yamato 2', 'TV', 1978, 'A year has passed since the Star Force returned to save the Earth but another danger now approaches from deep space. A gigantic White Comet hurtles toward our galaxy, obliterating everything in its path. But it is no ordinary comet—it is the deadly Comet Empire, conqueror of worlds... and Earth is the next target! Against orders, the Star Force blasts off to investigate, but even if they can get past the flagship Andromeda, they don\'t yet know the true nature of their new enemy!\r\n\r\n(Source: AniDB)', 'Group TAC', 26, 'https://cdn.myanimelist.net/images/anime/10/61239l.jpg', '2022-10-02 10:31:10'),
(33, 'Uchuu Senkan Yamato: Aratanaru Tabidachi', 'Special', 1979, 'It is the year 2201. The Yamato has returned from the devastating battle with Emperor Zordar and the Comet Empire. Sanada, Aihara, and Shima are released from the hospital, and go to pay their respects to the fallen crew members at Okita\'s memorial. They meet Tokugawa\'s son Tasuke, who says that he will be joining the crew once he graduates from cadet school. The next day at his graduation, he ends up capsizing a boat full of new cadets because they are all too busy staring at the Yamato to watch where they are going.\r\n\r\nAfter some problems during launch due to the new engine crew hitting the wrong switches and stalling the ship, the Yamato departs on what should be a simple training mission.', 'Group TAC', 1, 'https://cdn.myanimelist.net/images/anime/2/61237l.jpg', '2022-10-02 10:32:13'),
(34, 'Yamato yo Towa ni', 'Movie', 1980, 'The Black Nebula Empire attacks Earth and threatens to blow up the planet with a bomb they placed on Earth if counter attacked. Earths hopes rest on the Yamato crew as they go to the Black Nebula Planet and try to find a way to difuse the bomb before it\'s too late.\r\n\r\n(Source: ANN)', 'Toei Animation', 1, 'https://cdn.myanimelist.net/images/anime/8/83043l.jpg', '2022-10-02 10:33:00'),
(35, 'Choujikuu Yousai Macross: Ai Oboete Imasu ka', 'Movie', 1984, 'A.D. 2009 - The human race is in the middle of a three-way war with a race of giant humanoid aliens called the Zentraedi (male) and Meltrandi (female). After executing a space fold that sent it and part of South Atalia Island to the edge of the Solar System, the space fortress Macross is on its way back to Earth. During a small skirmish with Zentraedi forces, young pilot Hikaru Ichijo rescues idol singer Lynn Minmay and their relationship develops as they\'re stranded somewhere within the ship. But shortly after returning to Macross City, Minmay is captured by the Zentraedi, and Hikaru and female officer Misa Hayase end up back on Earth - only to view the aftermath of the destruction of their civilization. Only a song discovered eons ago - along with Minmay\'s voice - can determine the outcome of the war.\r\n\r\n(Source: Anime News Network)', 'Tatsunoko Production, Artland', 1, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1089-uoP83D60OHxP.jpg', '2022-10-02 10:34:11'),
(36, 'Megazone 23', 'OVA', 1985, 'Motorcycle enthusiast Shogo mistakenly comes into possession of a government prototype bike. Pursued by ruthless goverment agents he plans to save himself by exposing the bike to the public on a live TV show hosted by a popular singing star. But, even the lovely Eve has secrets of her own and the government has much more to hide than just a transforming military motorcycle. As Shogo begins to unravel the mystery of the bike, he discovers a reality-shattering secret about the city and the world he thought he knew.\r\n\r\n(Source: Anime News Network)', 'Artland, AIC, Artmic', 4, 'https://cdn.myanimelist.net/images/anime/1425/124086l.jpg', '2022-10-02 10:35:16'),
(37, 'A KITE', 'OVA', 1998, 'Sawa is a school girl, an orphan, and an assassin. She is being controlled by a corrupt cop who gives her targets to kill, detailing to her the crimes these men have committed in order to justify their death. Some of his power over Sawa has to do with her deceased parents and the promise of revenge. When another orphan, a teenage boy called Oburi, is brought in to assist Sawa, the two teenage killers form a bond of sorts. As they heal each other\'s emotional wounds, they begin to dream of a life that would not be spent under the shadows of murder.\r\n\r\n(Source: Anime News Network)', 'Arms', 2, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx320-uoswyrIq31bG.png', '2022-10-02 10:35:57'),
(38, 'Giant Robo THE ANIMATION: Chikyuu ga Seishi Suru Hi', 'OVA', 1992, '10 years ago Dr. Shizuma and his colleagues invented the Shizuma drive which is a revolutionizing new form of renewable and recyclable energy. Though they had to pay a heavy price for their success in a catastrophic accident that the world only wants to forget about. However, all is not well as the secret organization Big Fire is hell-bent on taking over the world. They have obtained two of three mysterious Shizuma drive samples with an unknown function, which are an integral part of their world domination plans. The third sample has however been stolen by Dr. Shizuma who during his escape is saved by Daisaku, Giant Robo and the Experts of Justice. Then a desperate struggle begins between the Experts of Justice and Big Fire for the control of the last sample as Big Fire unleashes their mightiest weapon, the Eye of Volger, upon the unsuspecting world. Soon everything points towards the hidden truth behind the accident 10 years ago as the starting point of everything.\r\n\r\n(Source: Anime News Network)', 'Phoenix Entertainment, Jupiter Films, Mu Animation Studio', 7, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx2321-ETrAaZnKGpUS.jpg', '2022-10-02 10:36:44'),
(39, 'Touch', 'TV', 1985, 'The story centers around three characters - Uesugi Kazuya, his twin older brother Tatsuya, and Asakura Minami. Kazuya is the darling of his town as he\'s talented, hardworking, and the ace pitcher for his middle school baseball team. Tatsuya is a hopeless slacker who\'s been living the life of giving up the spotlight to Kazuya, despite the fact that he may be more gifted than him. Minami is the beautiful childhood girlfriend and for all intents, sister from next door who treats both of them as equals. Society largely assumes Kazuya and Minami will become the perfect couple, including Tatsuya. Yet as time progresses, Tatsuya grows to realize that he\'s willing to sacrifice anything for the sake of his brother, except at the expense of giving up Minami to Kazuya. And thus the story is told of Tatsuya trying to prove himself over his established younger brother, how it affects the relationship between the three, and both brothers\' attempts to make Minami\'s lifelong dreams come true.', 'Group TAC', 101, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1065-Gga7D9IhqkLN.jpg', '2022-10-02 10:40:38'),
(40, 'MINKY MOMO in Yume ni Kakeru Hashi', 'OVA', 1993, 'A bridge\'s legend tells that when two people meet on it, they will surely meet again. Momo meets a boy who doesn\'t believe the legend, and promises that she will meet him again to prove it. As the year passes, she comes every day to wait for him, and becomes a small part of many people\'s lives.\r\n\r\n(Source: Anime News Network)', 'Studio Junio', 1, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx3462-4xLkDwIwm6NJ.jpg', '2022-10-02 10:41:06'),
(41, 'Taiyou no Kiba Dougram', 'TV', 1981, 'The story is centered around a small group of guerilla freedom fighters on a colonial planet named Deployer, who are known as the \"Deployer 7\", or \"Sun Fang\" team. In an unexpected coup, the elected Governor of Deployer becomes dictator and rules Deployer under martial law with the support of Earth\'s Federation. Fighting for independence from Earth\'s Federation influence, the freedom fighters begin a rebellion against the Federation\'s Combat Armors using a Combat Armor of their own: the Dougram.\r\n\r\n(Source: AniDB)', 'Sunrise', 75, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b2257-rKWjJXEqGjd2.jpg', '2022-10-02 10:41:53'),
(42, 'Ashita no Joe 2', 'TV', 1980, 'Yabuki Joe is left downhearted and hopeless after a certain tragic event. In attempt to put the past behind him, Joe leaves the gym behind and begins wandering. On his travels he comes across the likes of Wolf Kanagushi and Goromaki Gondo, men who unintentionally fan the dying embers inside him, leading him to putting his wanderings to an end. His return home puts Joe back on the path to boxing, but unknown to himself and his trainer, he now suffers deep-set issues holding him back from fighting. In attempt to quell those issues, Carlos Rivera, a world renowned boxer is invited from Venezuela to help Joe recover.', 'Tokyo Movie Shinsha', 47, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx2921-wxj62hpZVbuF.jpg', '2022-10-02 10:42:20'),
(43, 'Ashita no Joe', 'TV', 1970, 'Joe, a teenage orphan in the slums of the Doya streets, meets Danpei, a homeless, alcoholic ex-boxing coach. Danpei, seeing Joe\'s boxing talent, decides to train him. When Joe is sent to a terrible juvenile home for petty crimes, he meets Rikiishi who becomes his boxing rival. Danpei arrives at the home to help Joe to train in order to defeat Rikiishi. When Joe decides to seriously pursue boxing, Danpei cannot get a coaching license because of his reputation as a drunk.\r\n\r\n(Source: AnimeNfo)', 'Mushi Production', 79, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/nx2402-hbo1SbfcM5hm.jpg', '2022-10-02 10:42:39'),
(44, 'Urusei Yatsura 2: Beautiful Dreamer', 'Movie', 1984, 'In Urusei Yatsura: Beautiful Dreamer, Tomobiki High is in a frenzy to get ready for the school festival. Props need to be made, costumes designed, and maybe somewhere sleep to be had! Ataru, Lum, Shutaro, Shinobu, and the rest of Class 2-4 are determined to not be outdone this year, and they\'re rushing to make the final preparations for tomorrow\'s grand opening.\r\n\r\nOnce they wake up the next morning, they continue their mad rush to get ready for tomorrow\'s grand opening. And then the next day... hey, isn\'t something strange going on? Silence lingers over the city, the buildings filled with nothing but dust and mold. Is this a dream? Or have the kids (and a few related adults) of Class 2-4 finally woken up? If they can spend each day having fun with each other, does it matter?\r\n\r\n(Source: Discotek)', 'Studio Pierrot', 1, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1921-YYKPVDPdHXbH.png', '2022-10-02 10:43:24'),
(45, 'Urusei Yatsura 4: Lum the Forever', 'Movie', 1986, 'Strange things begin happening in Tomobiki Town...\r\n\r\nWhen a great cherry tree, \"Tarozakura\" is cut down while Lum & Co. are making a movie, Lum loses her horns-and her powers! Thus begins the strangest and most lyrical of the Urusei Yatsura movies...\r\n\r\n(Source: AniDB)', 'Studio DEEN', 1, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/1923-F2EGuJX0bBJg.png', '2022-10-02 10:43:44'),
(46, 'Aikatsu!', 'TV', 2012, 'An idol\'s brilliance illuminates the dreams of humanity. Starlight Academy, a holy ground for celebrities in training, seeks to realize this belief. Behind its rigorous entrance requirements lie not only the top young stars in the entertainment business, but some of the best memories these students will ever have.\r\n\r\nOr so Aoi Kiriya believes. Alongside her best friend Ichigo, Aoi decides to apply for the prestigious private school in hopes of living up to the praise of the biggest idol in the world: Mizuki Kanzaki. As they journey through the numerous laughs, friendships, and heartbreaks that await them, can the two girls light up the lives of others as Mizuki has done for them?\r\n\r\nWhether it be chopping down Christmas trees, traversing obstacle courses, or even rock climbing, there\'s always a playful new adventure to be found in the world of Aikatsu!.\r\n\r\n[Written by MAL Rewrite]', 'Sunrise', 178, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx15061-LmFVCPOmUBaE.png', '2022-10-02 11:21:51'),
(47, 'DAICON IV Opening Animation', 'Music', 1983, 'A \"bunny girl\" crosses paths with iconic characters from comic books, live-action films, literature and animation.\r\n\r\n(Source: IMDB)', 'Gainax', 1, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx121664-W0B2xLXXNxpj.jpg', '2022-10-02 11:28:44'),
(48, 'Neon Genesis Evangelion', 'TV', 1995, 'Fifteen years after a cataclysmic event known as the Second Impact, the world faces a new threat: monstrous celestial beings called \"Angels\" invade Tokyo-3 one by one. Mankind is unable to defend themselves against the Angels despite utilizing their most advanced munitions and military tactics. The only hope for human salvation rests in the hands of NERV, a mysterious organization led by the cold Gendou Ikari. NERV operates giant humanoid robots dubbed \"Evangelions\" to combat the Angels with state-of-the-art advanced weaponry and protective barriers known as Absolute Terror Fields.\r\n\r\nYears after being abandoned by his father, Shinji Ikari, Gendou\'s 14-year-old son, returns to Tokyo-3. Shinji undergoes a perpetual internal battle against the deeply buried trauma caused by the loss of his mother and the emotional neglect he suffered at the hands of his father. Terrified to open himself up to another, Shinji\'s life is forever changed upon meeting 29-year-old Misato Katsuragi, a high-ranking NERV officer who shows him a free-spirited maternal kindness he has never experienced.\r\n\r\nA devastating Angel attack forces Shinji into action as Gendou reveals his true motive for inviting his son back to Tokyo-3: Shinji is the only child capable of efficiently piloting Evangelion Unit-01, a new robot that synchronizes with his biometrics. Despite the brutal psychological trauma brought about by piloting an Evangelion, Shinji defends Tokyo-3 against the angelic threat, oblivious to his father\'s dark machinations.\r\n\r\n[Written by MAL Rewrite]', 'Gainax', 26, 'https://cdn.myanimelist.net/images/anime/3/75616.jpg', '2022-10-02 11:29:59'),
(49, 'Neon Genesis Evangelion: The End of Evangelion', 'Movie', 1997, 'NERV faces a brutal attack from SEELE, but with Asuka in a coma, and Shinji in a nervous breakdown, things soon turn into the surreal. This movie provides a concurrent ending to the final two episodes of the show Neon Genesis Evangelion.\r\n\r\n(Source: IMDb)', 'Gainax', 1, 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx32-i4ijZI4MuPiV.jpg', '2022-10-02 11:30:51');

-- --------------------------------------------------------

--
-- Structure de la table `userlist`
--

CREATE TABLE `userlist` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `anime_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Déchargement des données de la table `userlist`
--

INSERT INTO `userlist` (`id`, `user_id`, `anime_id`) VALUES
(27, 6, 42),
(28, 6, 41),
(29, 6, 30),
(30, 6, 29),
(31, 6, 32),
(32, 6, 33),
(33, 6, 34),
(34, 6, 35),
(35, 6, 36),
(36, 6, 38),
(37, 6, 39),
(38, 6, 26),
(39, 6, 27),
(40, 6, 7),
(41, 6, 8),
(42, 6, 11),
(43, 6, 12),
(44, 6, 13),
(45, 6, 14),
(46, 6, 49),
(50, 6, 44);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(30) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_520_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `admin` int(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `password`, `created_at`, `admin`) VALUES
(6, 'admin', 'admin@gmail.com', '$2y$10$hv4MqTTpwu1pDcMxbtvZGeF2VSOCkXpv7.cIoSZsbXOrsQBY9PcPO', '2022-09-12 17:37:00', 1);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `animes`
--
ALTER TABLE `animes`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `userlist`
--
ALTER TABLE `userlist`
  ADD PRIMARY KEY (`id`),
  ADD KEY `anime_id` (`anime_id`),
  ADD KEY `user_id` (`user_id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `animes`
--
ALTER TABLE `animes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- AUTO_INCREMENT pour la table `userlist`
--
ALTER TABLE `userlist`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `userlist`
--
ALTER TABLE `userlist`
  ADD CONSTRAINT `userlist_ibfk_1` FOREIGN KEY (`anime_id`) REFERENCES `animes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `userlist_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
